Script started on 2020-10-23 17:45:11-06:00
]0;muhammad.adil@csa1:~/cpsc355/ProjectP1muhammad.adil@csa1:~/cpsc355/ProjectP1$ gcc myGame.c - o[K[Ko myGame -lm
]0;muhammad.adil@csa1:~/cpsc355/ProjectP1muhammad.adil@csa1:~/cpsc355/ProjectP1$ ./myGame Bob 1 1[K[K0 10
The board size is 10x10
Generating game board...
 13.66    -2.32    -8.93    14.01    12.01       !     -3.21   -14.37    13.53   -10.28   
  1.28     9.58     8.44       !    -12.17    12.66    10.35       !     -6.67    -1.53   
  0.68    11.53    -9.82       #      0.78    -4.31       !      1.27    -4.13    -1.51   
  5.62    -8.47    14.18    14.68   -12.46     8.19       !      2.33    11.82    11.76   
 10.06    -4.90     3.34     0.49    -6.52     9.17    -4.85   -14.16     7.87     6.48   
  2.31    -9.45     0.01    10.49    -8.63       #    -11.82   -10.53     2.07     2.05   
  5.96   -10.31    11.58     2.14   -13.63       #     -7.68       $      1.45   -13.86   
 14.36    -6.49    -0.76    -0.30    12.00    10.72    -9.14   -10.84    14.56       !    
 13.64    -1.13   -10.72    -4.35    -8.64    -1.35    -3.55    -2.46     6.12       *    
    !        #     -5.92    12.25    13.47     4.76    11.90     3.13     5.80     5.23   
The total negative numbers are 39/100 = 39.00% < 40.00%
----------------------------------The Game has Started!!----------------------------------
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
Lives: 3
Score: 0
Bombs: 5
To play enter 'P'. To view top scores enter 'T'. To exit program enter anything else
p
Enter an X coordinate:(between 0-9)
0
Enter an Y coordinate:(between 0-9. Enter -1 to quit.)
0
Bomb range is 2^0
Total uncovered score is 22.20
+ - X X X X X X X X 
+ + X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
Lives: 3
Score: 22.20
Bomb: 4
Enter an X coordinate:(between 0-9)
9
Enter an Y coordinate:(between 0-9. Enter -1 to quit.)
0
You found an extra life!!
Extra two points!!
Bomb range is 2^0
Total uncovered score is 36.71
+ - X X X X X X X X 
+ + X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
+ - X X X X X X X X 
! # X X X X X X X X 
Lives: 4
Score: 14.50
Bomb: 3
Enter an X coordinate:(between 0-9)
0
Enter an Y coordinate:(between 0-9. Enter -1 to quit.)
9
Bomb range is 2^0
Total uncovered score is 31.76
+ - X X X X X X + - 
+ + X X X X X X - - 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
+ - X X X X X X X X 
! # X X X X X X X X 
Lives: 4
Score: -4.95
Bomb: 2
Enter an X coordinate:(between 0-9)
9
Enter an Y coordinate:(between 0-9. Enter -1 to quit.)
9
Exit Key Found!! Good Job!!
Bomb range is 2^0
Total uncovered score is 48.91
+ - X X X X X X + - 
+ + X X X X X X - - 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
+ - X X X X X X + * 
! # X X X X X X + + 
Lives: 4
Score: 17.15
Bomb: 1
Bob has a score of 48.91. The time played is 11 seconds
How many top scores do you want(between 1 - 2)?(Enter 0 to exit program)
0
Exiting Program]0;muhammad.adil@csa1:~/cpsc355/ProjectP1muhammad.adil@csa1:~/cpsc355/ProjectP1$ ./myGame Tommy 15 15
The board size is 15x15
Generating game board...
 -4.11       !      1.27     6.40     8.18    -6.19     1.82       !    -13.34     8.87    12.84    10.94       *     11.96    14.92   
 11.63     7.20     1.41    14.61   -14.21    -5.19    -7.31     3.74    -8.76     3.48       #     -1.64       !     -3.63    -8.56   
  1.96    -5.13     5.33     3.63    14.14    -6.27    -6.19   -10.05    13.55    -7.95    -5.38     4.41   -13.12   -12.44    -1.63   
    !        #    -12.43     3.22    13.80    -8.64       !    -11.52    13.10   -10.72     9.96    13.21     5.64    11.47    -8.42   
    $     -4.57     4.45     2.41       #      0.59    14.14    -7.12     8.54     9.68     2.92   -14.84    -3.91     7.81    -9.28   
 12.46     9.62   -10.10       #     -5.16   -14.30    -8.61    -7.13    -7.82   -13.50     0.15       $        #    -12.21    13.61   
 -8.72       $     -8.95    13.73     5.27    -9.89    -3.68     1.41     0.99   -13.13    -6.91   -14.08    -9.97     7.19    11.73   
 -1.26     1.65     3.34     6.64     1.68       !     10.34    11.07    -8.95       $        $      9.20   -13.34       $     14.99   
    #    -11.44       #     -8.68       $      5.13    -0.57    -1.39   -11.46       #      3.47    -0.37   -13.66    11.50   -11.18   
    !     -7.76     8.47     1.41       !     -7.85    -0.41     9.23   -14.78     8.64    11.74       #     -0.16       !        !    
 -3.17       !    -13.38    -3.31   -10.01   -11.09       !      7.43     5.51    -9.65     7.85    -9.01     7.98    12.20       $    
 14.80    10.26    -5.27     5.27    -6.32    -6.38       $     11.27       $        #      1.91    14.59       !        !     12.99   
    #     -1.42    11.67   -13.90    13.27       !     -6.99       $      9.09       !    -12.57    -1.06   -10.49    13.42    -6.86   
 -8.00    10.22   -14.60     4.74    -2.51    -2.92       !     -5.10    -9.65       !     -4.47    10.26       $     -3.04    12.01   
 10.78    -3.56    -7.41     4.45     0.55   -12.14     6.11    11.56       $     11.81     3.87    13.44    14.84     2.03     3.43   
The total negative numbers are 89/225 = 39.56% < 40.00%
----------------------------------The Game has Started!!----------------------------------
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
Lives: 3
Score: 0
Bombs: 11
To play enter 'P'. To view top scores enter 'T'. To exit program enter anything else
p
Enter an X coordinate:(between 0-14)
0
Enter an Y coordinate:(between 0-14. Enter -1 to quit.)
0
You found an extra life!!
Bomb range is 2^0
Total uncovered score is 14.72
- ! X X X X X X X X X X X X X 
+ + X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
Lives: 4
Score: 14.72
Bomb: 10
Enter an X coordinate:(between 0-14)
14
Enter an Y coordinate:(between 0-14. Enter -1 to quit.)
14
Bomb range is 2^0
Total uncovered score is 29.15
- ! X X X X X X X X X X X X X 
+ + X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X - + 
X X X X X X X X X X X X X + + 
Lives: 4
Score: 14.43
Bomb: 9
Enter an X coordinate:(between 0-14)
5
Enter an Y coordinate:(between 0-14. Enter -1 to quit.)
5
Extra two points!!
Bomb range is 2^0
Total uncovered score is 9.51
- ! X X X X X X X X X X X X X 
+ + X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X # + + X X X X X X X X 
X X X X - - - X X X X X X X X 
X X X X + - - X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X - + 
X X X X X X X X X X X X X + + 
Lives: 4
Score: -19.64
Bomb: 8
Enter an X coordinate:(between 0-14)
11
Enter an Y coordinate:(between 0-14. Enter -1 to quit.)
6
You found an extra life!!
You found an extra life!!
Bomb range is 2^2
Total uncovered score is 3.74
- ! X X X X X X X X X X X X X 
+ + X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X # + + X X X X X X X X 
X X X X - - - X X X X X X X X 
X X X X + - - X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X - ! + X X X X X X X 
X X X X X - $ + X X X X X X X 
X X X X X ! - $ X X X X X X X 
X X X X X X X X X X X X X - + 
X X X X X X X X X X X X X + + 
Lives: 6
Score: -5.77
Bomb: 7
Enter an X coordinate:(between 0-14)
0
Enter an Y coordinate:(between 0-14. Enter -1 to quit.)
12
Exit Key Found!! Good Job!!
You found an extra life!!
Exit Key Found!! Good Job!!
Extra two points!!
Exit Key Found!! Good Job!!
Exit Key Found!! Good Job!!
Bomb range is 2^0
Total uncovered score is 45.42
- ! X X X X X X - + + + * + + 
+ + X X X X X X - + # - ! - - 
X X X X X X X X + - - + - - - 
X X X X X X X X + - + + + + - 
X X X X # + + X + + + - - + - 
X X X X - - - X X X X X X X X 
X X X X + - - X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X - ! + X X X X X X X 
X X X X X - $ + X X X X X X X 
X X X X X ! - $ X X X X X X X 
X X X X X X X X X X X X X - + 
X X X X X X X X X X X X X + + 
Lives: 7
Score: 41.68
Bomb: 6
Tommy has a score of 45.42. The time played is 23 seconds
How many top scores do you want(between 1 - 3)?(Enter 0 to exit program)
0
Exiting Program]0;muhammad.adil@csa1:~/cpsc355/ProjectP1muhammad.adil@csa1:~/cpsc355/ProjectP1$ ./myGame La[K[KAdam 11 11
The board size is 11x11
Generating game board...
    #     -1.35    -2.46   -11.66     6.33    -5.09     3.76    -8.70       #        $    -11.06   
 12.07     6.13       #     -0.35       #     10.74    -1.20    -6.55     8.59    -6.64     5.92   
 -8.11     0.71    -9.43     2.35    -3.28    -7.36     2.38     5.58    -9.29     1.79       *    
-13.77     6.25     8.14    10.56       !     -6.10       !        #     -3.61    -9.20    13.06   
    $     -9.78    -5.29       $        #     11.51    -3.57     9.55   -13.13       $        !    
  5.58    -7.09     3.80       $      3.55   -11.83     7.87    12.26     7.97    12.10     0.51   
 -1.90     4.66     1.67    10.00     6.52     2.65   -11.61       $     -2.29    -9.09   -12.46   
 10.42    -6.11   -11.50     3.92     8.32       !      8.79    10.67       #     -3.63   -14.42   
  3.30    -1.33     7.13     9.47   -11.46     1.40    -0.56       #        !        $      5.29   
  3.57     7.54    -6.18   -11.78    13.93    -8.86     3.93   -13.16    -3.32    -3.66    -1.27   
  3.18       #    -10.95     1.24     9.06       #      0.74   -12.58   -14.70   -13.96     4.09   
The total negative numbers are 48/121 = 39.67% < 40.00%
----------------------------------The Game has Started!!----------------------------------
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
Lives: 3
Score: 0
Bombs: 6
To play enter 'P'. To view top scores enter 'T'. To exit program enter anything else
p
Enter an X coordinate:(between 0-10)
0
Enter an Y coordinate:(between 0-10. Enter -1 to quit.)
0
Extra two points!!
Bomb range is 2^0
Total uncovered score is 18.86
# - X X X X X X X X X 
+ + X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
Lives: 3
Score: 18.86
Bomb: 5
Enter an X coordinate:(between 0-10)
1
Enter an Y coordinate:(between 0-10. Enter -1 to quit.)
9
Extra two points!!
Exit Key Found!! Good Job!!
Bomb range is 2^1
Total uncovered score is 10.17
# - X X X X X X # $ - 
+ + X X X X X X + - + 
X X X X X X X X - + * 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
X X X X X X X X X X X 
Lives: 3
Score: -8.69
Bomb: 4
Adam has a score of 10.17. The time played is 15 seconds
How many top scores do you want(between 1 - 4)?(Enter 0 to exit program)
4
Bob 48.91 11
Tommy 45.42 23
Razeen 39.97 9
Adam 10.17 15
]0;muhammad.adil@csa1:~/cpsc355/ProjectP1muhammad.adil@csa1:~/cpsc355/ProjectP1$ exit
exit

Script done on 2020-10-23 17:49:27-06:00
